### ISSUE TITLE
subscription-manager role gives error for missing rhsm_password when subscribing with Satellite

### ISSUE THREAD

**Issue by etsauer** [rhtconsulting/rhc-ose#163]
I invoke the subscription-manager role in a play like:

```
- name: Subscribe servers
  hosts: dns-servers
  roles:
  - { role: subscription-manager, when: hostvars.localhost.rhsm_register, tags: 'subscription-manager' }
```

My inventory contains:

```
[all:vars]

rhsm_register=yes
rhsm_server='casl-sat6-1.rhc-ose.labs.redhat.com'
rhsm_org='RHC-OSE'
rhsm_activationkey='OSEv3-Library'
rhsm_method='satellite'
```

When run, I get an error saying:

```
PLAY [Subscribe servers] ********************************************** 

GATHERING FACTS *************************************************************** 
ok: [casl-esauer-yolAIJxG-dns-server1]

TASK: [subscription-manager | Initialize rhsm_password variable if vars_prompt was used] *** 
fatal: [casl-esauer-yolAIJxG-dns-server1] => One or more undefined variables: 'dict object' has no attribute 'rhsm_password'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/role-openstack.retry

casl-esauer-yolAIJxG-dns-server1 : ok=1    changed=0    unreachable=1    failed=0   
localhost                  : ok=17   changed=5    unreachable=0    failed=0   
```

If i'm providing an activation key, then I shouldn't need to provide rhsm_password, correct?

cc: @vvaldez

**Comment by etsauer** [comment]
@vvaldez tried including a dummy value for `rhsm_password` to see if I get by it, but it looks like it then tries both subscription methods:

```
TASK: [subscription-manager | Register to Satellite using activation key] ***** 
skipping: [casl-esauer-R9xr3oH5-dns-server1]

TASK: [subscription-manager | Register using username and password] *********** 
skipping: [casl-esauer-R9xr3oH5-dns-server1] => (item={'skipped': True, 'censored': 'results hidden due to no_log parameter', 'changed': False})

```

Then eventually fails at the attach task since it's not successfully subscribed.

**Comment by vvaldez** [comment]
@etsauer looking into this now. First thing I see is that the variable is **rhsm_satellite** and no longer **rhsm_server** and the **rhsm_method** is no longer used, any chance that is an older version of the original PR? I also don't read in **rhsm_register** that is dynamically determined based on which parameters are set. When I run the latest subscription-manager role with those same variables you specified I get this:

```
TASK: [Initialize Subscription Manager fact] ********************************** 
ok: [localhost] => {"ansible_facts": {"rhsm_register": true}}

TASK: [Determine if Subscription Manager should be used] ********************** 
skipping: [localhost]

TASK: [Validate Subscription Manager organization is set] ********************* 
skipping: [localhost]

TASK: [Validate Subscription Manager authentication is defined] *************** 
skipping: [localhost]

TASK: [Validate activation key and Hosted are not requested together] ********* 
failed: [localhost] => {"failed": true}
msg: Cannot register to RHSM Hosted with 'rhsm_activationkey'

FATAL: all hosts have already failed -- aborting
```

This should be caught in the pre_tasks lines 42-49:

```
- name: "Validate activation key and Hosted are not requested together"
  fail: msg="Cannot register to RHSM Hosted with 'rhsm_activationkey'"
  when:
    - rhsm_satellite is undefined or rhsm_satellite is none or rhsm_satellite|trim == ''
    - rhsm_activationkey is defined
    - rhsm_activationkey is not none
    - rhsm_activationkey|trim != ''
    - rhsm_register
```

Do you have the pre_task called before the role in the play? You may be able to simply add:

```
pre_tasks:
  - include: roles/subscription-manager/pre_tasks/pre_tasks.yml
```

It shouldn't be trying both key and password, those tasks say **skipping**, did it try to execute one or both? You can try -vv on the playbook run. However, I do see where a problem may occur if using a key and no password, I will work on addressing that now.
